#!/bin/bash

user=`/usr/bin/whoami`
#./autogen.sh && ./configure --prefix=/home/$user/netembryo --localstatedir=/home/$user/netembryo/var --with-ssl --enable-warnings --enable-debug && ./build
#./autogen.sh && ./configure --prefix=/home/$user/netembryo --localstatedir=/home/$user/netembryo/var --enable-warnings --enable-debug --enable-libao=no && ./build
./autogen.sh && ./configure --enable-warnings --enable-debug --enable-libao=no && ./build
